#!/bin/bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  tools.sh split <file> [-s <size>] [-n <count>] [-p <prefix>] [-a <algo>]
  tools.sh merge  <prefix> [-o <output>] [-v]
  tools.sh verify <checksum-file>
  tools.sh commit [<message>] [<remote>]
  tools.sh help | -h

Commands:
  split   Split <file> into multiple parts and generate a checksum file. Exactly one of the following must be given:
            -s <size>    per-part size, with optional suffix (e.g. 10M, 512K, 1G)
            -n <count>   number of parts to split into
            -p <prefix>  prefix of generated parts (default: <file>.part)
            -a <algo>    checksum algorithm: md5, sha1 or sha256 (default: sha256)
            The checksum file records hashes of the original file and every part,
            so it can verify integrity before split, after split and after merge.
  merge   Merge split parts back into one file.
            <prefix>    prefix of the parts to merge, or a glob (e.g. "data.part00*")
            -o <output> output file (default: <prefix> with trailing ".part" stripped)
            -v          verify the merged output against the checksum file after merging
  verify  Verify integrity against a checksum file generated by the split command.
            It checks every split part; run it again after merging (into the original
            filename) to confirm the merged file matches the original.
  commit  Delegate to commit.sh to commit and push all changes.
            Optional <message> and <remote> are passed through to commit.sh.
EOF
}

check_file() {
  if [ ! -f "$1" ]; then
    echo "[ERROR] File not found: $1"
    exit 1
  fi
}

split_file() {
  local file="" size="" count="" prefix="" algo="sha256"
  while [ $# -gt 0 ]; do
    case "$1" in
      -s) size="${2:-}"; shift 2 ;;
      -n) count="${2:-}"; shift 2 ;;
      -p) prefix="${2:-}"; shift 2 ;;
      -a) algo="${2:-}"; shift 2 ;;
      *) file="$1"; shift ;;
    esac
  done

  file="${file//\\//}"
  prefix="${prefix//\\//}"

  if [ -z "$file" ]; then
    echo "[ERROR] No file specified."
    usage
    exit 1
  fi
  check_file "$file"

  case "$algo" in
    md5|sha1|sha256) ;;
    *) echo "[ERROR] Invalid algorithm: $algo (use md5, sha1 or sha256)"; exit 1 ;;
  esac
  if ! command -v "${algo}sum" >/dev/null 2>&1; then
    echo "[ERROR] ${algo}sum not available."
    exit 1
  fi

  if [ -z "$size" ] && [ -z "$count" ]; then
    echo "[ERROR] Specify one of -s <size> or -n <count>."
    usage
    exit 1
  fi
  if [ -n "$size" ] && [ -n "$count" ]; then
    echo "[ERROR] Specify only one of -s <size> or -n <count>."
    usage
    exit 1
  fi

  if [ -n "$count" ]; then
    if [[ ! "$count" =~ ^[0-9]+$ ]]; then
      echo "[ERROR] Invalid count: $count"
      exit 1
    fi
  fi
  if [ -n "$size" ]; then
    if [[ ! "$size" =~ ^[0-9]+([.][0-9]+)?[A-Za-z]{0,3}$ ]]; then
      echo "[ERROR] Invalid size: $size"
      exit 1
    fi
  fi

  if [ -z "$prefix" ]; then
    prefix="${file}.part"
  fi

  echo "[INFO] Splitting $file ..."
  if [ -n "$size" ]; then
    split -b "$size" -d -a 3 "$file" "$prefix"
  else
    split -n "$count" -d -a 3 "$file" "$prefix"
  fi

  local parts checksum_file
  parts=$(ls "$prefix"* 2>/dev/null | wc -l || true)
  checksum_file="${file}.${algo}"
  {
    "${algo}sum" "$file"
    "${algo}sum" "$prefix"* 2>/dev/null || true
  } > "$checksum_file"
  echo "[SUCCESS] $file split into $parts parts with prefix: $prefix"
  echo "[SUCCESS] Checksum file generated: $checksum_file (original file + parts)"
}

checksum_cmd_of() {
  case "$1" in
    *.md5|*.MD5) echo "md5sum" ;;
    *.sha1|*.SHA1) echo "sha1sum" ;;
    *.sha256|*.SHA256) echo "sha256sum" ;;
    *) echo "md5sum" ;;
  esac
}

find_checksum() {
  local base="$1" f algo
  for algo in md5 sha1 sha256; do
    for f in "${base}.${algo}" "${base}.${algo^^}"; do
      if [ -f "$f" ]; then
        echo "$f"
        return 0
      fi
    done
  done
  return 1
}

run_check() {
  local checksum="${1:-}" cmd status
  if [ -z "$checksum" ]; then
    echo "[ERROR] No checksum file found."
    return 1
  fi
  check_file "$checksum"
  cmd=$(checksum_cmd_of "$checksum")
  echo "[INFO] Verifying with $cmd against $checksum ..."
  if "$cmd" -c "$checksum"; then
    status=0
  else
    status=$?
  fi
  return $status
}

merge_file() {
  local output="" verify=""
  local -a files=()
  while [ $# -gt 0 ]; do
    case "$1" in
      -o) output="${2//\\//}"; shift 2 ;;
      -v) verify="1"; shift ;;
      *) files+=("${1//\\//}"); shift ;;
    esac
  done

  if [ ${#files[@]} -eq 0 ]; then
    echo "[ERROR] No prefix specified."
    usage
    exit 1
  fi

  local list=() pattern
  if [ ${#files[@]} -eq 1 ]; then
    case "${files[0]}" in
      *[*?[]*) pattern="${files[0]}" ;;
      *) pattern="${files[0]}"* ;;
    esac
    for m in ${pattern}; do
      case "$m" in
        *[*?[]*) continue ;;
      esac
      list+=("$m")
    done
    if [ ${#list[@]} -eq 0 ]; then
      echo "[ERROR] No parts found matching: ${files[0]}"
      exit 1
    fi
  else
    list=("${files[@]}")
  fi

  mapfile -t list < <(printf '%s\n' "${list[@]}" | sort | tr -d '\r')

  local first parts
  first="${list[0]}"
  parts=${#list[@]}
  output="${output:-${first%.part*}}"

  echo "[INFO] Merging $parts parts into $output ..."
  cat "${list[@]}" > "$output"
  echo "[SUCCESS] Merged into: $output"

  if [ -n "$verify" ]; then
    local checksum_file
    if checksum_file=$(find_checksum "$output"); then
      if run_check "$checksum_file"; then
        echo "[SUCCESS] Merged file verified: $output matches the original."
      else
        echo "[ERROR] Merged file verification FAILED."
        exit 1
      fi
    else
      echo "[WARN] No checksum file found for $output, skipped verification."
    fi
  fi
}

verify_file() {
  local checksum="${1:-}"
  checksum="${checksum//\\//}"
  if [ -z "$checksum" ]; then
    echo "[ERROR] No checksum file specified."
    usage
    exit 1
  fi
  if run_check "$checksum"; then
    echo "[SUCCESS] All recorded files verified OK."
  else
    echo "[ERROR] Verification FAILED."
    exit 1
  fi
}

commit_update() {
  local dir
  dir=$(cd "$(dirname "$0")" && pwd)
  bash "$dir/commit.sh" "$@"
}

case "${1:-}" in
  split) shift; split_file "$@" ;;
  merge) shift; merge_file "$@" ;;
  verify) shift; verify_file "$@" ;;
  commit|update) shift; commit_update "$@" ;;
  -h|--help|help|"") usage; exit 0 ;;
  *) echo "[ERROR] Unknown command: ${1:-}" >&2; usage; exit 1 ;;
esac